tap 'homebrew/cask-versions'

brew 'bash'
brew 'bash-completion2'
brew 'tmux'
brew 'vim'
brew 'neovim'
brew 'git'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'python3'
brew 'ruby'
brew 'go'
brew 'openssl'
brew 'pkg-config'
brew 'htop'
brew 'ffmpeg'
brew 'coreutils'
brew 'tree'

cask 'slack-beta'
cask 'iterm2-beta'
cask 'google-chrome-beta'
cask 'spotify'
cask '1password'
cask 'ngrok'
