#!/usr/bin/env bash

publish() {
  if [[ $# -eq 0 ]]; then
    git push -u origin $(git branch --show-current);
  elif [[ $1 == "-f" || $1 == "--force" ]]; then
    git push --force-with-lease origin $(git branch --show-current);
  fi
}

publish "$@"
