alias docker="podman"
alias rsa="$HOME/dotfiles/scripts/kill.rb"
alias cup="$HOME/dotfiles/scripts/cup"
alias bu="$HOME/dotfiles/scripts/bu"
alias latest="chruby ruby-3.4.7"
alias c="clear"
alias ls="ls -Ga"
alias vim="/opt/homebrew/bin/nvim"
alias vi="/opt/homebrew/bin/nvim"
alias cat="bat --paging=never"
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
alias python=python3
alias kl="kill -9 %1"
alias ftp="files-to-prompt"
alias tssh="TERM=xterm-256color tailscale ssh"
