alias rsa="$HOME/dotfiles/scripts/kill.rb"
alias latest="chruby ruby"
alias c="clear"
alias ls="ls -Ga"
alias vim="/opt/homebrew/bin/nvim"
alias vi="/opt/homebrew/bin/nvim"
alias cat="bat --paging=never"
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
alias python=python3
alias kl="kill -9 %1"
